### ISSUE TITLE
Ask questions aleatory

### ISSUE THREAD

**Issue by CesarHerreraG** [ChristianPauly/flashcards#2]
Don't ask the questions allways in the same order.

**Comment by ChristianPauly** [comment]
There is no order. Every iteration the app chooses randomly one of the flashcards from the selected stack. There is no intelligent algorithm behind that. If you have got the same order multiple times, its just luck :-D

**Comment by CesarHerreraG** [comment]
Sorry. I didn't check it enoufgh. Ok.

**Comment by ChristianPauly** [comment]
No problem. Im happy it works for you :-)
